add {"name":"tttttt","coordinates":{"x":-490,"y":54},"numberOfParticipants":1,"albumsCount":5,"genre":"JAZZ","studio":{"name":"tttttt","address":"tttttt"}}
add {"name":"tt","coordinates":{"x":-490,"y":0},"numberOfParticipants":1,"albumsCount":5,"genre":"JAZZ","studio":{"name":"tt","address":"tttttt"}}
add {"name":"ttttttttttttttttttttttt","coordinates":{"x":-490,"y":-54},"numberOfParticipants":1,"albumsCount":5,"genre":"JAZZ","studio":{"name":"tt","address":"tttttt"}}
add {"name":"ttttttt","coordinates":{"x":-490,"y":-108},"numberOfParticipants":1,"albumsCount":5,"genre":"JAZZ","studio":{"name":"tt","address":"tttttt"}}
add {"name":"ttttt","coordinates":{"x":-490,"y":-162},"numberOfParticipants":1,"albumsCount":5,"genre":"JAZZ","studio":{"name":"tt","address":"tttttt"}}
add {"name":"tt","coordinates":{"x":-490,"y":-216},"numberOfParticipants":1,"albumsCount":5,"genre":"JAZZ","studio":{"name":"tt","address":"tttttt"}}